// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Project.Domain.MySql;

namespace Project.Infrastructure.Models
{
    public partial class LocaldbContext : DbContext
    {
        public LocaldbContext()
        {
        }

        public LocaldbContext(DbContextOptions<LocaldbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Project.Domain.Entities.Project> PROJECT { get; set; }
        public virtual DbSet<Statuscode> Statuscode { get; set; }
        public virtual DbSet<Task> TASK { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
              //  optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=D:\\Documents\\Programming\\ProjectManagementSystem\\ProjectManagementSystem\\Project.Core\\PMS.mdf;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Domain.MySql.Project>().ToTable("Project");
            modelBuilder.Entity<Domain.MySql.Statuscode>().ToTable("Statuscode");
            modelBuilder.Entity<Domain.MySql.Task>().ToTable("Task");            
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}